"""initial multi-tenant academic schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def _uuid(): return postgresql.UUID(as_uuid=True)

def _enum(name, values): return postgresql.ENUM(*values, name=name, create_type=False)


def upgrade():
    bind = op.get_bind()
    for name, values in [
        ("organization_type", ["university", "college", "institute", "other"]),
        ("organization_status", ["active", "inactive", "suspended", "trial"]),
        ("user_status", ["active", "inactive", "suspended"]),
        ("academic_status", ["active", "inactive", "graduated", "suspended", "withdrawn"]),
        ("enrollment_status", ["enrolled", "dropped", "completed", "withdrawn"]),
        ("attendance_status", ["present", "absent", "late", "excused"]),
        ("assessment_type", ["assignment", "quiz", "midterm", "final", "project", "other"]),
        ("notification_type", ["general", "academic", "attendance", "grade", "system"]),
        ("target_type", ["gpa", "cgpa"]),
    ]:
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)

    op.create_table("organizations",
        sa.Column("id", _uuid(), primary_key=True), sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(120), nullable=False), sa.Column("organization_type", _enum("organization_type", ["university","college","institute","other"]), nullable=False),
        sa.Column("status", _enum("organization_status", ["active","inactive","suspended","trial"]), nullable=False),
        sa.Column("timezone", sa.String(64), nullable=False, server_default="UTC"), sa.Column("locale", sa.String(16), nullable=False, server_default="en-US"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("slug", name="uq_organizations_slug"))
    op.create_table("organization_settings",
        sa.Column("organization_id", _uuid(), nullable=False), sa.Column("minimum_attendance_percentage", sa.Float(), nullable=False, server_default="75"),
        sa.Column("grading_scale", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")), sa.Column("academic_rules", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="RESTRICT"), sa.PrimaryKeyConstraint("organization_id"),
        sa.CheckConstraint("minimum_attendance_percentage >= 0 AND minimum_attendance_percentage <= 100", name="ck_settings_attendance_pct"))
    op.create_table("users",
        sa.Column("id", _uuid(), primary_key=True), sa.Column("organization_id", _uuid(), nullable=True), sa.Column("email", sa.String(320), nullable=False),
        sa.Column("full_name", sa.String(200), nullable=False), sa.Column("status", _enum("user_status", ["active","inactive","suspended"]), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="RESTRICT"), sa.UniqueConstraint("email"), sa.UniqueConstraint("organization_id","id",name="uq_users_org_id"))

    def tenant_table(name, columns, constraints=(), indexes=()):
        cols = [sa.Column("id", _uuid(), primary_key=True), sa.Column("organization_id", _uuid(), nullable=False),
                sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now())] + columns
        op.create_table(name, *cols, sa.ForeignKeyConstraint(["organization_id"],["organizations.id"],ondelete="RESTRICT"), sa.UniqueConstraint("organization_id", "id", name=f"uq_{name}_org_id"), *constraints)
        for idx in indexes: op.create_index(idx[0], name, list(idx[1:]))

    tenant_table("campuses", [sa.Column("name",sa.String(160),nullable=False),sa.Column("code",sa.String(40),nullable=False),sa.Column("address",sa.Text()),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true())], [sa.UniqueConstraint("organization_id","code",name="uq_campus_org_code")], [("ix_campuses_org","organization_id")])
    tenant_table("departments", [sa.Column("campus_id",_uuid(),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("code",sa.String(40),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true())], [sa.ForeignKeyConstraint(["organization_id","campus_id"],["campuses.organization_id","campuses.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","code",name="uq_department_org_code")], [("ix_departments_org","organization_id")])
    tenant_table("programs", [sa.Column("department_id",_uuid(),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("code",sa.String(40),nullable=False),sa.Column("duration_years",sa.Integer()),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true())], [sa.ForeignKeyConstraint(["organization_id","department_id"],["departments.organization_id","departments.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","code",name="uq_program_org_code")], [("ix_programs_org_department","organization_id","department_id")])
    tenant_table("academic_sessions", [sa.Column("code",sa.String(40),nullable=False),sa.Column("name",sa.String(100),nullable=False),sa.Column("start_date",sa.Date()),sa.Column("end_date",sa.Date()),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true())], [sa.UniqueConstraint("organization_id","code",name="uq_session_org_code"),sa.CheckConstraint("end_date IS NULL OR start_date IS NULL OR end_date >= start_date",name="ck_session_dates")], [("ix_sessions_org","organization_id")])
    tenant_table("semesters", [sa.Column("academic_session_id",_uuid(),nullable=False),sa.Column("code",sa.String(40),nullable=False),sa.Column("name",sa.String(100),nullable=False),sa.Column("start_date",sa.Date()),sa.Column("end_date",sa.Date()),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true())], [sa.ForeignKeyConstraint(["organization_id","academic_session_id"],["academic_sessions.organization_id","academic_sessions.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","academic_session_id","code",name="uq_semester_session_code"),sa.CheckConstraint("end_date IS NULL OR start_date IS NULL OR end_date >= start_date",name="ck_semester_dates")], [("ix_semesters_org_session","organization_id","academic_session_id")])
    tenant_table("classrooms", [sa.Column("campus_id",_uuid(),nullable=False),sa.Column("building",sa.String(100)),sa.Column("room_code",sa.String(40),nullable=False),sa.Column("capacity",sa.Integer(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true())], [sa.ForeignKeyConstraint(["organization_id","campus_id"],["campuses.organization_id","campuses.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","campus_id","room_code",name="uq_classroom_room"),sa.CheckConstraint("capacity > 0",name="ck_classroom_capacity_positive")], [("ix_classrooms_org_campus","organization_id","campus_id")])
    tenant_table("students", [sa.Column("user_id",_uuid()),sa.Column("student_number",sa.String(60),nullable=False),sa.Column("program_id",_uuid(),nullable=False),sa.Column("academic_session_id",_uuid(),nullable=False),sa.Column("admission_date",sa.Date()),sa.Column("date_of_birth",sa.Date()),sa.Column("phone",sa.String(40)),sa.Column("status",_enum("academic_status",["active","inactive","graduated","suspended","withdrawn"]),nullable=False)], [sa.ForeignKeyConstraint(["organization_id","user_id"],["users.organization_id","users.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","program_id"],["programs.organization_id","programs.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","academic_session_id"],["academic_sessions.organization_id","academic_sessions.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","student_number",name="uq_student_org_number")], [("ix_students_org_program","organization_id","program_id"),("ix_students_org_user","organization_id","user_id")])
    tenant_table("teachers", [sa.Column("user_id",_uuid()),sa.Column("employee_number",sa.String(60),nullable=False),sa.Column("department_id",_uuid(),nullable=False),sa.Column("phone",sa.String(40)),sa.Column("status",_enum("academic_status",["active","inactive","graduated","suspended","withdrawn"]),nullable=False)], [sa.ForeignKeyConstraint(["organization_id","user_id"],["users.organization_id","users.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","department_id"],["departments.organization_id","departments.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","employee_number",name="uq_teacher_org_employee")], [("ix_teachers_org_department","organization_id","department_id")])
    tenant_table("guardians", [sa.Column("user_id",_uuid()),sa.Column("phone",sa.String(40)),sa.Column("relationship_label",sa.String(60))], [sa.ForeignKeyConstraint(["organization_id","user_id"],["users.organization_id","users.id"],ondelete="RESTRICT")], [("ix_guardians_org_user","organization_id","user_id")])
    tenant_table("student_guardians", [sa.Column("student_id",_uuid(),nullable=False),sa.Column("guardian_id",_uuid(),nullable=False)], [sa.ForeignKeyConstraint(["organization_id","student_id"],["students.organization_id","students.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["organization_id","guardian_id"],["guardians.organization_id","guardians.id"],ondelete="CASCADE"),sa.UniqueConstraint("organization_id","student_id","guardian_id",name="uq_student_guardian")], [("ix_student_guardians_org_student","organization_id","student_id")])
    tenant_table("courses", [sa.Column("department_id",_uuid(),nullable=False),sa.Column("course_code",sa.String(40),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("description",sa.Text()),sa.Column("credit_hours",sa.Numeric(4,2),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true())], [sa.ForeignKeyConstraint(["organization_id","department_id"],["departments.organization_id","departments.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","course_code",name="uq_course_org_code"),sa.CheckConstraint("credit_hours > 0 AND credit_hours <= 20",name="ck_course_credit_hours")], [("ix_courses_org_department","organization_id","department_id")])
    tenant_table("course_prerequisites", [sa.Column("course_id",_uuid(),nullable=False),sa.Column("prerequisite_course_id",_uuid(),nullable=False)], [sa.ForeignKeyConstraint(["organization_id","course_id"],["courses.organization_id","courses.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["organization_id","prerequisite_course_id"],["courses.organization_id","courses.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","course_id","prerequisite_course_id",name="uq_course_prerequisite"),sa.CheckConstraint("course_id <> prerequisite_course_id",name="ck_course_no_self_prerequisite")])
    tenant_table("sections", [sa.Column("course_id",_uuid(),nullable=False),sa.Column("semester_id",_uuid(),nullable=False),sa.Column("program_id",_uuid()),sa.Column("section_code",sa.String(40),nullable=False),sa.Column("capacity",sa.Integer()),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true())], [sa.ForeignKeyConstraint(["organization_id","course_id"],["courses.organization_id","courses.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","semester_id"],["semesters.organization_id","semesters.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","program_id"],["programs.organization_id","programs.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","semester_id","course_id","section_code",name="uq_section_offering"),sa.CheckConstraint("capacity IS NULL OR capacity > 0",name="ck_section_capacity")], [("ix_sections_org_semester","organization_id","semester_id"),("ix_sections_org_course","organization_id","course_id")])
    tenant_table("enrollments", [sa.Column("student_id",_uuid(),nullable=False),sa.Column("section_id",_uuid(),nullable=False),sa.Column("enrolled_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("status",_enum("enrollment_status",["enrolled","dropped","completed","withdrawn"]),nullable=False)], [sa.ForeignKeyConstraint(["organization_id","student_id"],["students.organization_id","students.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","section_id"],["sections.organization_id","sections.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","student_id","section_id",name="uq_enrollment_student_section")], [("ix_enrollments_org_student","organization_id","student_id"),("ix_enrollments_org_section","organization_id","section_id")])
    tenant_table("attendance_records", [sa.Column("enrollment_id",_uuid(),nullable=False),sa.Column("attendance_date",sa.Date(),nullable=False),sa.Column("status",_enum("attendance_status",["present","absent","late","excused"]),nullable=False),sa.Column("recorded_by_user_id",_uuid(),nullable=False),sa.Column("note",sa.Text())], [sa.ForeignKeyConstraint(["organization_id","enrollment_id"],["enrollments.organization_id","enrollments.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","recorded_by_user_id"],["users.organization_id","users.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","enrollment_id","attendance_date",name="uq_attendance_enrollment_date")], [("ix_attendance_org_enrollment_date","organization_id","enrollment_id","attendance_date")])
    tenant_table("assessments", [sa.Column("section_id",_uuid(),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("assessment_type",_enum("assessment_type",["assignment","quiz","midterm","final","project","other"]),nullable=False),sa.Column("max_marks",sa.Numeric(8,2),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True))], [sa.ForeignKeyConstraint(["organization_id","section_id"],["sections.organization_id","sections.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","section_id","name",name="uq_assessment_section_name"),sa.CheckConstraint("max_marks > 0",name="ck_assessment_max_marks")], [("ix_assessments_org_section","organization_id","section_id")])
    tenant_table("grades", [sa.Column("enrollment_id",_uuid(),nullable=False),sa.Column("assessment_id",_uuid(),nullable=False),sa.Column("marks_obtained",sa.Numeric(8,2),nullable=False),sa.Column("letter_grade",sa.String(8)),sa.Column("grade_point",sa.Numeric(5,2))], [sa.ForeignKeyConstraint(["organization_id","enrollment_id"],["enrollments.organization_id","enrollment_id"],ondelete="RESTRICT") if False else sa.ForeignKeyConstraint(["organization_id","enrollment_id"],["enrollments.organization_id","enrollments.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","assessment_id"],["assessments.organization_id","assessments.id"],ondelete="RESTRICT"),sa.UniqueConstraint("organization_id","enrollment_id","assessment_id",name="uq_grade_enrollment_assessment"),sa.CheckConstraint("marks_obtained >= 0",name="ck_grade_marks_nonnegative"),sa.CheckConstraint("grade_point IS NULL OR grade_point >= 0",name="ck_grade_point_nonnegative")], [("ix_grades_org_enrollment","organization_id","enrollment_id")])
    tenant_table("timetable_entries", [sa.Column("section_id",_uuid(),nullable=False),sa.Column("teacher_id",_uuid()),sa.Column("classroom_id",_uuid()),sa.Column("day_of_week",sa.Integer(),nullable=False),sa.Column("start_time",sa.Time(),nullable=False),sa.Column("end_time",sa.Time(),nullable=False)], [sa.ForeignKeyConstraint(["organization_id","section_id"],["sections.organization_id","sections.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","teacher_id"],["teachers.organization_id","teachers.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","classroom_id"],["classrooms.organization_id","classrooms.id"],ondelete="RESTRICT"),sa.CheckConstraint("day_of_week BETWEEN 0 AND 6",name="ck_timetable_day"),sa.CheckConstraint("end_time > start_time",name="ck_timetable_time")], [("ix_timetable_org_section_day","organization_id","section_id","day_of_week"),("ix_timetable_org_teacher_day","organization_id","teacher_id","day_of_week"),("ix_timetable_org_classroom_day","organization_id","classroom_id","day_of_week")])
    tenant_table("notifications", [sa.Column("recipient_user_id",_uuid(),nullable=False),sa.Column("notification_type",_enum("notification_type",["general","academic","attendance","grade","system"]),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("is_read",sa.Boolean(),nullable=False,server_default=sa.false())], [sa.ForeignKeyConstraint(["organization_id","recipient_user_id"],["users.organization_id","users.id"],ondelete="RESTRICT")], [("ix_notifications_org_recipient_read","organization_id","recipient_user_id","is_read")])
    tenant_table("academic_targets", [sa.Column("student_id",_uuid(),nullable=False),sa.Column("semester_id",_uuid()),sa.Column("target_type",_enum("target_type",["gpa","cgpa"]),nullable=False),sa.Column("target_value",sa.Numeric(4,2),nullable=False),sa.Column("note",sa.Text())], [sa.ForeignKeyConstraint(["organization_id","student_id"],["students.organization_id","students.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["organization_id","semester_id"],["semesters.organization_id","semesters.id"],ondelete="RESTRICT"),sa.CheckConstraint("target_value >= 0 AND target_value <= 4.0",name="ck_target_value")], [("ix_targets_org_student","organization_id","student_id")])


def downgrade():
    for name in ["academic_targets","notifications","timetable_entries","grades","assessments","attendance_records","enrollments","sections","course_prerequisites","courses","student_guardians","guardians","teachers","students","classrooms","semesters","academic_sessions","programs","departments","campuses","users","organization_settings","organizations"]:
        op.drop_table(name)
    bind = op.get_bind()
    for name in ["target_type","notification_type","assessment_type","attendance_status","enrollment_status","academic_status","user_status","organization_status","organization_type"]:
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)
