import {useEffect,useState} from 'react';
import {cms} from '../../services/cmsService';
import {courseApi} from '../../services/courseService';
const empty={course_code:'',title:'',description:'',credit_hours:3,course_type:'theory',department_id:''};
export default function CoursesPage(){const [courses,setCourses]=useState([]),[deps,setDeps]=useState([]),[form,setForm]=useState(empty),[edit,setEdit]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{setCourses((await courseApi.courses()).data);setDeps((await cms.list('departments')).data)}catch(e){setError(e.response?.data?.detail||'Could not load courses')}} useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const d={...form,credit_hours:Number(form.credit_hours)}; if(edit)await courseApi.updateCourse(edit,d);else await courseApi.createCourse(d);setForm(empty);setEdit(null);await load()}catch(e){setError(e.response?.data?.detail||'Save failed')}finally{setBusy(false)}}
 async function archive(id){if(!confirm('Archive this course?'))return;try{await courseApi.archiveCourse(id);await load()}catch(e){setError(e.response?.data?.detail||'Archive failed')}}
 return <><div className="d-flex justify-content-between mb-3"><div><h1 className="h3">Courses</h1><p className="text-muted">Tenant-scoped course catalogue</p></div></div>{error&&<div className="alert alert-danger">{error}</div>}<div className="card shadow-sm mb-4"><form className="card-body row g-3" onSubmit={save}><div className="col-md-2"><label className="form-label">Code</label><input className="form-control" value={form.course_code} onChange={e=>setForm({...form,course_code:e.target.value})} required/></div><div className="col-md-4"><label className="form-label">Title</label><input className="form-control" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></div><div className="col-md-3"><label className="form-label">Department</label><select className="form-select" value={form.department_id} onChange={e=>setForm({...form,department_id:e.target.value})} required><option value="">Select</option>{deps.map(d=><option key={d.id} value={d.id}>{d.name} ({d.code})</option>)}</select></div><div className="col-md-1"><label className="form-label">Credits</label><input type="number" step="0.5" min="0.1" max="20" className="form-control" value={form.credit_hours} onChange={e=>setForm({...form,credit_hours:e.target.value})} required/></div><div className="col-md-2"><label className="form-label">Type</label><select className="form-select" value={form.course_type} onChange={e=>setForm({...form,course_type:e.target.value})}>{['core','elective','lab','theory','project','other'].map(x=><option key={x}>{x}</option>)}</select></div><div className="col-12"><label className="form-label">Description</label><textarea className="form-control" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="col-12"><button className="btn btn-dark" disabled={busy}>{busy?'Saving…':edit?'Update Course':'Create Course'}</button>{edit&&<button type="button" className="btn btn-outline-secondary ms-2" onClick={()=>{setEdit(null);setForm(empty)}}>Cancel</button>}</div></form></div><div className="card shadow-sm"><div className="table-responsive"><table className="table table-hover mb-0"><thead><tr><th>Code</th><th>Title</th><th>Department</th><th>Credits</th><th>Type</th><th>Status</th><th/></tr></thead><tbody>{courses.map(c=><tr key={c.id}><td>{c.course_code}</td><td>{c.title}</td><td>{deps.find(d=>d.id===c.department_id)?.name||c.department_id}</td><td>{c.credit_hours}</td><td>{c.course_type}</td><td>{c.is_active?'Active':'Archived'}</td><td><button className="btn btn-sm btn-outline-secondary me-2" onClick={()=>{setEdit(c.id);setForm(c)}}>Edit</button><button className="btn btn-sm btn-outline-danger" onClick={()=>archive(c.id)}>Archive</button></td></tr>)}{!courses.length&&<tr><td colSpan="7" className="text-center py-4 text-muted">No courses found.</td></tr>}</tbody></table></div></div></>}
